# 定义换肤函数
def change_skin(self):
    # 5个皮肤循环  默认是bluesky
    self.change_skin_num  += 1
    num = self.change_skin_num % 5

    if num == 1:
        # 切换到windmill  ok
        self.start_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(164, 114, 190);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(117, 81, 136);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(141, 98, 163);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 30pt \"楷体\";\n"
                                        "    border-radius: 60px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.exit_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(164, 114, 190);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(117, 81, 136);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(141, 98, 163);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 18pt \"楷体\";\n"
                                        "    border-radius: 20px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.change_skin_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(164, 114, 190);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(117, 81, 136);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(141, 98, 163);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 18pt \"楷体\";\n"
                                        "    border-radius: 20px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.get_info_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(164, 114, 190);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(117, 81, 136);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(141, 98, 163);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 18pt \"楷体\";\n"
                                        "    border-radius: 20px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.setStyleSheet("QWidget#Form{\n"
                           "    border-image: url(:/start_choice_ui/images/start_choice_ui_bg__windmill.jpg);\n"
                           "}")
        self.title_zh.setStyleSheet("background-color: transparent;\n"
                                    "font: 33pt \"黑体\" ;\n"
                                    "color: rgb(111, 68, 142);\n"
                                    "border: none;\n"
                                    "\n"
                                    "")
        self.title_en.setStyleSheet("background-color: transparent;\n"
                                    "color: rgb(111, 68, 142);\n"
                                    "font: 17px \"Sitka Display\";\n"
                                    "border: none;")

    if num == 2:
        # 切换到fly  ok
        self.start_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(133, 194, 211);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(112, 163, 177);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(124, 181, 197);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 30pt \"楷体\";\n"
                                        "    border-radius: 60px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.exit_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(133, 194, 211);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(112, 163, 177);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(124, 181, 197);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 18pt \"楷体\";\n"
                                        "    border-radius: 20px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.change_skin_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(133, 194, 211);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(112, 163, 177);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(124, 181, 197);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 18pt \"楷体\";\n"
                                        "    border-radius: 20px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.get_info_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(133, 194, 211);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(112, 163, 177);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(124, 181, 197);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 18pt \"楷体\";\n"
                                        "    border-radius: 20px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.setStyleSheet("QWidget#Form{\n"
                           "    border-image: url(:/start_choice_ui/images/start_choice_ui_bg_fly.jpg);\n"
                           "}")
        self.title_zh.setStyleSheet("background-color: transparent;\n"
                                    "font: 33pt \"黑体\" ;\n"
                                    "color: rgb(61, 86, 132);\n"
                                    "border: none;\n"
                                    "\n"
                                    "")
        self.title_en.setStyleSheet("background-color: transparent;\n"
                                    "color: rgb(61, 86, 132);\n"
                                    "font: 17px \"Sitka Display\";\n"
                                    "border: none;")


    if num == 3:
        # 切换到west_lake ok
        self.start_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(239, 127, 165);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(191, 102, 132);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(216, 115, 147);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 30pt \"楷体\";\n"
                                        "    border-radius: 60px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.exit_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(239, 127, 165);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(191, 102, 132);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(216, 115, 147);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 18pt \"楷体\";\n"
                                        "    border-radius: 20px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.change_skin_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(239, 127, 165);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(191, 102, 132);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(216, 115, 147);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 18pt \"楷体\";\n"
                                        "    border-radius: 20px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.get_info_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(239, 127, 165);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(191, 102, 132);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(216, 115, 147);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 18pt \"楷体\";\n"
                                        "    border-radius: 20px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.setStyleSheet("QWidget#Form{\n"
                           "    border-image: url(:/start_choice_ui/images/start_choice_ui_bg_West Lake.jpg);\n"
                           "}")
        self.title_zh.setStyleSheet("background-color: transparent;\n"
                                    "font: 33pt \"黑体\" ;\n"
                                    "color: rgb(175, 46, 72);\n"
                                    "border: none;\n"
                                    "\n"
                                    "")
        self.title_en.setStyleSheet("background-color: transparent;\n"
                                    "color: rgb(175, 46, 72);\n"
                                    "font: 17px \"Sitka Display\";\n"
                                    "border: none;")

    if num == 4:
        # 切换到wheat  ok
        self.start_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(238, 111, 79);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(197, 92, 65);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(212, 101, 71);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 30pt \"楷体\";\n"
                                        "    border-radius: 60px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.exit_button.setStyleSheet("QPushButton:hover {\n"
                                       "    background-color: rgb(238, 111, 79);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed {\n"
                                       "    \n"
                                       "    background-color: rgb(197, 92, 65);\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton {\n"
                                       "    background-color: rgb(212, 101, 71);\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    font: 18pt \"楷体\";\n"
                                       "    border-radius: 20px;\n"
                                       "    border: 4px;\n"
                                       "}")
        self.change_skin_button.setStyleSheet("QPushButton:hover {\n"
                                              "    background-color: rgb(238, 111, 79);\n"
                                              "}\n"
                                              "\n"
                                              "QPushButton:pressed {\n"
                                              "    \n"
                                              "    background-color: rgb(197, 92, 65);\n"
                                              "}\n"
                                              "\n"
                                              "QPushButton {\n"
                                              "    background-color: rgb(212, 101, 71);\n"
                                              "    color: rgb(255, 255, 255);\n"
                                              "    font: 18pt \"楷体\";\n"
                                              "    border-radius: 20px;\n"
                                              "    border: 4px;\n"
                                              "}")
        self.get_info_button.setStyleSheet("QPushButton:hover {\n"
                                           "    background-color: rgb(238, 111, 79);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:pressed {\n"
                                           "    \n"
                                           "    background-color: rgb(197, 92, 65);\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton {\n"
                                           "    background-color: rgb(212, 101, 71);\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "    font: 18pt \"楷体\";\n"
                                           "    border-radius: 20px;\n"
                                           "    border: 4px;\n"
                                           "}")
        self.setStyleSheet("QWidget#Form{\n"
                           "    border-image: url(:/start_choice_ui/images/start_choice_ui_bg_wheat.jpg);\n"
                           "}")
        self.title_zh.setStyleSheet("background-color: transparent;\n"
                                    "font: 33pt \"黑体\" ;\n"
                                    "color: rgb(132, 44, 27);\n"
                                    "border: none;\n"
                                    "\n"
                                    "")
        self.title_en.setStyleSheet("background-color: transparent;\n"
                                    "color: rgb(132, 44, 27);\n"
                                    "font: 17px \"Sitka Display\";\n"
                                    "border: none;")

    if num == 0:
        # 切换回bluesky
        self.start_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(58, 189, 236);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(27, 87, 126);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(28, 120, 167);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 30pt \"楷体\";\n"
                                        "    border-radius: 60px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.exit_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(58, 189, 236);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(27, 87, 126);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(28, 120, 167);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 18pt \"楷体\";\n"
                                        "    border-radius: 20px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.change_skin_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(58, 189, 236);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(27, 87, 126);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(28, 120, 167);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 18pt \"楷体\";\n"
                                        "    border-radius: 20px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.get_info_button.setStyleSheet("QPushButton:hover {\n"
                                        "    background-color: rgb(58, 189, 236);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    \n"
                                        "    background-color: rgb(27, 87, 126);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton {\n"
                                        "    background-color: rgb(28, 120, 167);\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 18pt \"楷体\";\n"
                                        "    border-radius: 20px;\n"
                                        "    border: 4px;\n"
                                        "}")
        self.setStyleSheet("QWidget#Form{\n"
                           "    border-image: url(:/start_choice_ui/images/start_choice_ui_bg__bluesky.jpg);\n"
                           "}")
        self.title_zh.setStyleSheet("background-color: transparent;\n"
                                    "font: 33pt \"黑体\" ;\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "border: none;\n"
                                    "\n"
                                    "")
        self.title_en.setStyleSheet("background-color: transparent;\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "font: 17px \"Sitka Display\";\n"
                                    "border: none;")


